#!/usr/bin/env bash
#
# Show pinot hostname of the board
#
# Usage: pinot-hostname [-p PORT]
#   -p PORT   Set name of serial PORT for connected board.

function usage() {
  echo "Show pinot hostname of the board"
  echo ""
  echo "Usage: pinot-hostname [-v] [-p PORT]"
  echo "  -p PORT Set name of serial PORT for connected board."
  echo "  -v      Verbose mode."
} >&2

OPT_VERBOSE=False

while getopts "dhp:v" flag
do
  case $flag in
    # getopts sets '?' to flag on error.
    \?|h) OPT_ERROR=1 ;;
    d)    DEBUG=1 ;;
    p)    OPT_PORT="$OPTARG" ;;
    v)    OPT_VERBOSE=True ;;
  esac
done
shift $(( $OPTIND - 1 ))

# set default port
if [ -n "$OPT_PORT" ]; then
  export AMPY_PORT="$OPT_PORT"
fi

# check unknown option and count args.
if [ "$OPT_ERROR" = 1 -o $# -ne 0 ]; then
  usage
  exit 1
fi

ampy run <(cat <<EOF
import network
import binascii
verbose = $OPT_VERBOSE
nic = network.WLAN()
cnf = nic.ifconfig()
mac = nic.config('mac')
hostname = 'pinot-' + str(binascii.hexlify(mac)[6:], 'ascii')
if verbose:
  print('inet', cnf[0], 'netmask', cnf[1], 'gateway', cnf[2])
  print('mac:', str(binascii.hexlify(mac, ':'), 'ascii'))
  print('hostname:', hostname)
else:
  print(hostname)
EOF
     ) | sed 's/\r$//'
